# Generated by Django 3.2.5 on 2021-12-09 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detoxa_services', '0010_kit_kitcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitcategory',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
