# Generated by Django 3.2.5 on 2021-12-10 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detoxa_services', '0012_alter_kitcategory_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kit',
            name='image',
        ),
        migrations.CreateModel(
            name='KitImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(blank=True, max_length=2000)),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detoxa_services.kit')),
            ],
        ),
    ]
