# Generated by Django 3.2.5 on 2021-12-11 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detoxa_services', '0013_auto_20211210_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.IntegerField()),
                ('image', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='subscription_type',
        ),
        migrations.AddField(
            model_name='transactions',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='detoxa_services.subscriptions'),
        ),
    ]
