# Generated by Django 3.2.5 on 2021-12-11 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detoxa_services', '0014_auto_20211211_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptions',
            name='image',
        ),
        migrations.CreateModel(
            name='SubscriptionsImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField()),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detoxa_services.subscriptions')),
            ],
        ),
    ]
