# Generated by Django 3.2.5 on 2021-12-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detoxa_services', '0015_auto_20211211_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='duration',
            field=models.CharField(default='', max_length=256),
        ),
    ]
