# Generated by Django 3.2.5 on 2021-12-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detoxa_services', '0016_alter_subscriptions_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='subscription',
        ),
        migrations.AddField(
            model_name='transactions',
            name='subscription_type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
