# Generated by Django 3.2.5 on 2021-12-11 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detoxa_services', '0017_auto_20211211_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionsimages',
            name='subscription',
        ),
        migrations.DeleteModel(
            name='Subscriptions',
        ),
        migrations.DeleteModel(
            name='SubscriptionsImages',
        ),
    ]
