# Generated by Django 3.2.5 on 2021-12-13 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detoxa_services', '0018_auto_20211211_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='detoxa_services.users'),
        ),
        migrations.AddField(
            model_name='users',
            name='is_doctor',
            field=models.BooleanField(default=False),
        ),
    ]
