# Generated by Django 3.2.5 on 2021-12-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detoxa_services', '0019_auto_20211213_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='currency',
            field=models.CharField(default='INR', max_length=20),
        ),
        migrations.AddField(
            model_name='transactions',
            name='order_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='payment_gateway',
            field=models.CharField(default='Razorpay', max_length=20),
        ),
        migrations.AddField(
            model_name='transactions',
            name='payment_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='signature',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Success', 'Success'), ('Declined ', 'Declined'), ('Retry ', 'Retry')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='transactions',
            name='subscription_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='subscription_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='transaction_datetime',
            field=models.DateTimeField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='subscription_type',
            field=models.CharField(choices=[('Parent', 'Parent'), ('Corporate', 'Corporate'), ('School', 'School'), ('Society', 'Society')], max_length=100, null=True),
        ),
    ]
