# Generated by Django 3.2.5 on 2021-12-16 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detoxa_services', '0021_auto_20211215_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
