# Generated by Django 3.2.5 on 2021-12-16 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detoxa_services', '0022_promocode_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='slot',
            field=models.CharField(default='', max_length=100),
        ),
    ]
