# Generated by Django 3.2.5 on 2021-12-19 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detoxa_services', '0024_appointment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreport',
            name='report_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='detoxa_services.learnabilitytracker'),
        ),
        migrations.AlterField(
            model_name='userreport',
            name='report_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
