# Generated by Django 3.2.5 on 2021-12-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detoxa_services', '0025_auto_20211219_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreport',
            name='age',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userreport',
            name='height',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userreport',
            name='weight',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
