# Generated by Django 3.2.5 on 2021-12-21 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detoxa_services', '0028_alter_appointment_child'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='child',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child', to='detoxa_services.users'),
        ),
    ]
