# Generated by Django 3.2.5 on 2021-12-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detoxa_services', '0029_alter_appointment_child'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreport',
            name='report_image_url',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='userreport',
            name='report_name',
            field=models.CharField(default='', max_length=150),
        ),
    ]
