# Generated by Django 3.2.5 on 2021-12-22 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detoxa_services', '0030_auto_20211222_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='detoxa_services.users'),
        ),
    ]
