# Generated by Django 3.2.5 on 2021-12-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detoxa_services', '0031_doctors_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='kit',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
