# Generated by Django 3.2.5 on 2021-12-23 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detoxa_services', '0032_kit_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kit',
            old_name='status',
            new_name='active',
        ),
    ]
