# Generated by Django 3.2.5 on 2021-12-23 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detoxa_services', '0033_rename_status_kit_active'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserReport',
            new_name='UserLearnabilityReport',
        ),
        migrations.CreateModel(
            name='UserGrowthReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(default='', max_length=150)),
                ('report_image_url', models.CharField(default='', max_length=500)),
                ('description', models.TextField()),
                ('height', models.CharField(blank=True, default='', max_length=100)),
                ('age', models.CharField(blank=True, default='', max_length=100)),
                ('weight', models.CharField(blank=True, default='', max_length=100)),
                ('gender', models.CharField(default='', max_length=256)),
                ('bmi', models.CharField(blank=True, max_length=10, null=True)),
                ('report_date', models.DateTimeField(auto_now_add=True)),
                ('report', models.CharField(default='', max_length=5000)),
                ('is_downloaded', models.BooleanField(default=False)),
                ('child_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detoxa_services.users')),
                ('parent_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grwoth_report_parent_user', to='detoxa_services.users')),
                ('report_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='detoxa_services.learnabilitytracker')),
            ],
        ),
    ]
