# Generated by Django 3.2.5 on 2021-12-23 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detoxa_services', '0034_auto_20211223_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergrowthreport',
            name='report_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='detoxa_services.childtracker'),
        ),
    ]
