# Generated by Django 3.2.5 on 2021-12-25 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detoxa_services', '0035_alter_usergrowthreport_report_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='kit',
            name='image_1',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='kit',
            name='image_2',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='kit',
            name='image_3',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='kit',
            name='image_4',
            field=models.URLField(blank=True),
        ),
    ]
