# Generated by Django 3.2.5 on 2021-12-29 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detoxa_services', '0037_auto_20211229_0407'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=256)),
                ('state', models.CharField(max_length=256)),
                ('country', models.CharField(max_length=256)),
                ('zipcode', models.CharField(max_length=256)),
                ('phone', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=256)),
                ('image', models.URLField()),
                ('total_no_of_students', models.IntegerField(default=0)),
                ('total_no_of_teachers', models.IntegerField(default=0)),
                ('total_no_of_non_teaching_staff', models.IntegerField(default=0)),
                ('total_no_of_flats', models.IntegerField(default=0)),
                ('total_no_of_employee', models.IntegerField(default=0)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='detoxa_services.users')),
            ],
        ),
    ]
