# Generated by Django 3.2.5 on 2021-12-31 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detoxa_services', '0043_alter_appointment_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='eyesighttracker',
            name='child',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eye_sight_child', to='detoxa_services.users'),
        ),
    ]
