# Generated by Django 3.2.5 on 2021-12-31 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detoxa_services', '0044_eyesighttracker_child'),
    ]

    operations = [
        migrations.AddField(
            model_name='handeyetracker',
            name='child',
            field=models.ForeignKey(db_column='child_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hand_eye_child_id', to='detoxa_services.users'),
        ),
    ]
