# Generated by Django 3.2.5 on 2021-12-31 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detoxa_services', '0047_auto_20211231_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationUserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Student', 'Student'), ('Teacher', 'Teacher'), ('Non-Teaching Staff', 'Non-Teaching Staff'), ('Flat', 'Flat'), ('Employee', 'Employee')], max_length=256)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_id', to='detoxa_services.organizations')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_user_id', to='detoxa_services.users')),
            ],
        ),
    ]
