# Generated by Django 3.2.5 on 2022-01-01 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detoxa_services', '0049_auto_20220101_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergrowthreport',
            name='parent_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grwoth_report_parent_user', to='detoxa_services.users'),
        ),
        migrations.AlterField(
            model_name='usergrowthreport',
            name='report_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='detoxa_services.childtracker'),
        ),
        migrations.CreateModel(
            name='UserHandEyeCoordinationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(default='', max_length=150)),
                ('report_image_url', models.CharField(default='', max_length=500)),
                ('description', models.TextField()),
                ('height', models.CharField(blank=True, default='', max_length=100)),
                ('age', models.CharField(blank=True, default='', max_length=100)),
                ('weight', models.CharField(blank=True, default='', max_length=100)),
                ('gender', models.CharField(default='', max_length=256)),
                ('bmi', models.CharField(blank=True, max_length=10, null=True)),
                ('report_date', models.DateTimeField(auto_now_add=True)),
                ('report', models.CharField(default='', max_length=5000)),
                ('is_downloaded', models.BooleanField(default=False)),
                ('child_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detoxa_services.users')),
                ('parent_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handeye_report_parent_user', to='detoxa_services.users')),
                ('report_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='detoxa_services.handeyetracker')),
            ],
        ),
    ]
