# Generated by Django 3.2.5 on 2022-01-01 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detoxa_services', '0050_auto_20220101_0809'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodNutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=200)),
                ('lunch', models.JSONField()),
                ('dinner', models.JSONField()),
                ('brakfast', models.JSONField()),
                ('current_height', models.CharField(max_length=200)),
                ('current_weight', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detoxa_services.users')),
                ('parent_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_nutrition_parent_user', to='detoxa_services.users')),
            ],
        ),
    ]
