# Generated by Django 3.2.5 on 2022-01-01 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detoxa_services', '0051_foodnutrition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodnutrition',
            old_name='brakfast',
            new_name='breakfast',
        ),
    ]
