# Generated by Django 3.2.5 on 2022-01-03 13:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('detoxa_services', '0052_rename_brakfast_foodnutrition_breakfast'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationuser',
            name='admission_number',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='organizationuser',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2022, 1, 3, 13, 25, 46, 208377, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizationuser',
            name='father_email',
            field=models.EmailField(default='father@email.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizationuser',
            name='father_name',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='organizationuser',
            name='father_phone',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='organizationuser',
            name='flat_number',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='organizationuser',
            name='mother_email',
            field=models.EmailField(default='mother@email.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizationuser',
            name='mother_name',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='organizationuser',
            name='mother_phone',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='organizationuser',
            name='user_class',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='organizationuser',
            name='user_section',
            field=models.CharField(default='', max_length=256),
        ),
    ]
