# Generated by Django 3.2.5 on 2022-01-07 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detoxa_services', '0054_auto_20220104_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='is_organization_admin',
            new_name='is_company_admin',
        ),
    ]
