# Generated by Django 3.2.5 on 2022-01-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detoxa_services', '0055_rename_is_organization_admin_users_is_company_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eyesighttracker',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='eyesighttracker',
            name='test_name',
        ),
        migrations.AddField(
            model_name='eyesighttracker',
            name='test_name_answer',
            field=models.JSONField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
