# Generated by Django 3.2.5 on 2022-01-15 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detoxa_services', '0058_users_is_hospital_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usereyesightreport',
            old_name='report_type',
            new_name='report_id',
        ),
    ]
