# Generated by Django 3.2.5 on 2022-01-27 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detoxa_services', '0062_usermotorskillsreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorskilltracker',
            name='child_user',
            field=models.ForeignKey(db_column='motor_skill_child_user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_motor_skill_child_user', to='detoxa_services.users'),
        ),
    ]
