# Generated by Django 3.2.5 on 2022-02-05 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detoxa_services', '0063_alter_motorskilltracker_child_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizations',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organizationuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
