# Generated by Django 3.2.5 on 2022-02-10 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detoxa_services', '0064_auto_20220205_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eyesighttracker',
            name='eye_side',
        ),
        migrations.AddField(
            model_name='eyesighttracker',
            name='test_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
