# Generated by Django 3.2.5 on 2022-02-10 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detoxa_services', '0065_auto_20220210_0447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eyesighttracker',
            name='created',
        ),
    ]
