# Generated by Django 3.2.5 on 2022-02-10 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detoxa_services', '0067_eyesighttracker_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eyesighttracker',
            name='test_name_answer',
        ),
        migrations.RemoveField(
            model_name='eyesighttracker',
            name='test_type',
        ),
    ]
