# Generated by Django 3.2.5 on 2022-02-10 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detoxa_services', '0068_auto_20220210_0453'),
    ]

    operations = [
        migrations.AddField(
            model_name='eyesighttracker',
            name='test_name_answer',
            field=models.JSONField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eyesighttracker',
            name='test_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
