# Generated by Django 3.2.5 on 2022-02-10 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detoxa_services', '0069_auto_20220210_0453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eyesighttracker',
            name='test_type',
        ),
    ]
