# Generated by Django 3.2.5 on 2022-02-10 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detoxa_services', '0070_remove_eyesighttracker_test_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='eyesighttracker',
            name='test_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
