# Generated by Django 3.2.5 on 2022-02-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detoxa_services', '0071_eyesighttracker_test_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hospitaluser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
