# Generated by Django 3.2.5 on 2022-02-12 14:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('detoxa_services', '0073_remove_eyesighttracker_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='eyesighttracker',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
