# Generated by Django 3.2.5 on 2022-02-12 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detoxa_services', '0074_eyesighttracker_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eyesighttracker',
            name='child',
        ),
        migrations.RemoveField(
            model_name='eyesighttracker',
            name='created',
        ),
        migrations.RemoveField(
            model_name='eyesighttracker',
            name='test_name_answer',
        ),
        migrations.RemoveField(
            model_name='eyesighttracker',
            name='test_type',
        ),
        migrations.RemoveField(
            model_name='eyesighttracker',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='eyesighttracker',
            name='user',
        ),
    ]
