# Generated by Django 3.2.5 on 2022-02-12 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detoxa_services', '0076_auto_20220212_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eyesighttracker',
            name='eye_side',
        ),
    ]
