# Generated by Django 3.2.5 on 2022-02-12 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detoxa_services', '0077_remove_eyesighttracker_eye_side'),
    ]

    operations = [
        migrations.AddField(
            model_name='eyesighttracker',
            name='eye_side',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
