# Generated by Django 3.2.5 on 2022-02-12 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detoxa_services', '0078_eyesighttracker_eye_side'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eyesighttracker',
            name='eye_side',
        ),
    ]
