# Generated by Django 3.2.5 on 2022-04-03 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detoxa_services', '0086_useranalyticalreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='HairTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('child_user', models.ForeignKey(db_column='child_user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_hair_child_user', to='detoxa_services.users')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='detoxa_services.users')),
            ],
            options={
                'db_table': 'hair_tracker',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SkinTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('child_user', models.ForeignKey(db_column='child_user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skin_child_user', to='detoxa_services.users')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='detoxa_services.users')),
            ],
            options={
                'db_table': 'skin_tracker',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserSkinReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(default='', max_length=150)),
                ('report_image_url', models.CharField(default='', max_length=500)),
                ('description', models.TextField()),
                ('height', models.CharField(blank=True, default='', max_length=100)),
                ('age', models.CharField(blank=True, default='', max_length=100)),
                ('weight', models.CharField(blank=True, default='', max_length=100)),
                ('gender', models.CharField(default='', max_length=256)),
                ('bmi', models.CharField(blank=True, max_length=10, null=True)),
                ('report_date', models.DateTimeField(auto_now_add=True)),
                ('report', models.CharField(default='', max_length=5000)),
                ('is_downloaded', models.BooleanField(default=False)),
                ('child_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detoxa_services.users')),
                ('parent_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skin_report_parent_user', to='detoxa_services.users')),
                ('report_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='detoxa_services.skintracker')),
            ],
        ),
        migrations.CreateModel(
            name='UserHairReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(default='', max_length=150)),
                ('report_image_url', models.CharField(default='', max_length=500)),
                ('description', models.TextField()),
                ('height', models.CharField(blank=True, default='', max_length=100)),
                ('age', models.CharField(blank=True, default='', max_length=100)),
                ('weight', models.CharField(blank=True, default='', max_length=100)),
                ('gender', models.CharField(default='', max_length=256)),
                ('bmi', models.CharField(blank=True, max_length=10, null=True)),
                ('report_date', models.DateTimeField(auto_now_add=True)),
                ('report', models.CharField(default='', max_length=5000)),
                ('is_downloaded', models.BooleanField(default=False)),
                ('child_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detoxa_services.users')),
                ('parent_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hair_report_parent_user', to='detoxa_services.users')),
                ('report_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='detoxa_services.hairtracker')),
            ],
        ),
        migrations.CreateModel(
            name='SkinTrackerSectionAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(choices=[('Reading', 'Reading'), ('Spelling and Writing', 'Spelling and Writing'), ('Math & Logic', 'Math & Logic'), ('Emotion & Self-Control', 'Emotion & Self-Control'), ('Listening', 'Listening'), ('Attention', 'Attention')], max_length=50)),
                ('answer', models.IntegerField(choices=[('5', '5'), ('4', '4'), ('3', '3'), ('2', '4'), ('1', '5')], default='5')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('skin_tracker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skin_tracker_id', to='detoxa_services.skintracker')),
            ],
            options={
                'db_table': 'skin_tracker_section_answers',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HairTrackerSectionAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(choices=[('Reading', 'Reading'), ('Spelling and Writing', 'Spelling and Writing'), ('Math & Logic', 'Math & Logic'), ('Emotion & Self-Control', 'Emotion & Self-Control'), ('Listening', 'Listening'), ('Attention', 'Attention')], max_length=50)),
                ('answer', models.IntegerField(choices=[('5', '5'), ('4', '4'), ('3', '3'), ('2', '4'), ('1', '5')], default='5')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('hair_tracker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_hair_tracker_id', to='detoxa_services.hairtracker')),
            ],
            options={
                'db_table': 'hair_tracker_section_answers',
                'managed': True,
            },
        ),
    ]
