# Generated by Django 3.2.5 on 2022-04-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detoxa_services', '0087_hairtracker_hairtrackersectionanswers_skintracker_skintrackersectionanswers_userhairreport_userskinr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('Email', 'Email'), ('SMS', 'SMS'), ('WhatsApp Notification', 'WhatsApp Notification')], max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
