# Generated by Django 3.2.5 on 2022-04-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detoxa_services', '0090_auto_20220406_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='from_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='to_date',
            field=models.DateField(),
        ),
    ]
