# Generated by Django 3.2.5 on 2022-04-09 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detoxa_services', '0091_auto_20220406_2255'),
    ]

    operations = [
        migrations.CreateModel(
            name='TherapistCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'therapist_category',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='users',
            name='is_therapist',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Therapist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('degree_name', models.CharField(max_length=50, null=True)),
                ('experience', models.CharField(max_length=100, null=True)),
                ('therapist_image_url', models.CharField(default='', max_length=500)),
                ('therapist_image', models.CharField(default='', max_length=5000)),
                ('therapist_time_slots', models.CharField(max_length=4000, null=True)),
                ('therapist_fee', models.IntegerField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('therapist_category', models.ForeignKey(db_column='therapist_category_id', on_delete=django.db.models.deletion.CASCADE, to='detoxa_services.therapistcategory')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='detoxa_services.users')),
            ],
            options={
                'db_table': 'therapist',
                'managed': True,
            },
        ),
    ]
