# Generated by Django 3.2.5 on 2022-04-10 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detoxa_services', '0092_auto_20220409_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDatabaseForNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=255)),
            ],
        ),
    ]
