# Generated by Django 3.2.5 on 2022-04-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detoxa_services', '0093_userdatabasefornotification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motorskilltrackersectionanswers',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='motorskilltrackersectionanswers',
            name='section_name',
        ),
        migrations.AddField(
            model_name='motorskilltrackersectionanswers',
            name='age_group',
            field=models.CharField(choices=[('2-3 Months', '2-3 Months'), ('3 Months to 1 Yr', '3 Months to 1 Yr'), ('1 Yr to 3 Yr', '1 Yr to 3 Yr'), ('3 Yr to 10 Yr', '3 Yr to 10 Yr')], default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motorskilltrackersectionanswers',
            name='answers',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
    ]
