# Generated by Django 3.2.5 on 2022-04-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detoxa_services', '0094_auto_20220411_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendedMeals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
                ('image_url', models.URLField(null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='motorskilltrackersectionanswers',
            name='age_group',
            field=models.CharField(blank=True, choices=[('2-3 Months', '2-3 Months'), ('3 Months to 1 Yr', '3 Months to 1 Yr'), ('1 Yr to 3 Yr', '1 Yr to 3 Yr'), ('3 Yr to 10 Yr', '3 Yr to 10 Yr')], max_length=50, null=True),
        ),
    ]
