# Generated by Django 3.2.5 on 2022-04-16 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detoxa_services', '0095_auto_20220416_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccinationAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Booked', 'Booked'), ('Done', 'Done'), ('OverDue', 'OverDue'), ('Upcoming', 'Upcoming'), ('Cancelled', 'Cancelled')], default='Upcoming', max_length=50)),
                ('vaccination_date', models.DateField(null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(db_column='child_id', on_delete=django.db.models.deletion.CASCADE, related_name='fk_vaccine_child_id', to='detoxa_services.users')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detoxa_services.users')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detoxa_services.vaccinationdata')),
            ],
            options={
                'db_table': 'vaccination_appointment',
                'managed': True,
            },
        ),
    ]
