# Generated by Django 3.2.5 on 2022-04-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detoxa_services', '0096_vaccinationappointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccinationAppointmentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
