# Generated by Django 3.2.5 on 2022-04-16 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detoxa_services', '0097_vaccinationappointmentstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialization',
            name='specialist_image',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='therapistcategory',
            name='therapist_image',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.CreateModel(
            name='TherapySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=3000)),
                ('date', models.DateField()),
                ('slot', models.CharField(default='', max_length=100)),
                ('fees', models.IntegerField(default=500)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Rescheduled', 'Rescheduled'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('is_promo_code_applied', models.BooleanField(default=False)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child', to='detoxa_services.users')),
                ('promo_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='detoxa_services.promocode')),
                ('therapist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='therapist_id', to='detoxa_services.therapist')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='detoxa_services.users')),
            ],
            options={
                'db_table': 'therapy_session',
                'managed': True,
            },
        ),
    ]
