# Generated by Django 3.2.5 on 2022-04-16 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detoxa_services', '0098_auto_20220416_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapysession',
            name='child',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_id', to='detoxa_services.users'),
        ),
    ]
