# Generated by Django 3.2.5 on 2022-04-17 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detoxa_services', '0099_alter_therapysession_child'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMedicalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_url', models.CharField(default='', max_length=500)),
                ('report_date', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='detoxa_services.organizations')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detoxa_services.users')),
            ],
        ),
    ]
