# Generated by Django 3.2.5 on 2022-04-23 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detoxa_services', '0100_usermedicalreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendedmeals',
            name='para_1',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recommendedmeals',
            name='para_2',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recommendedmeals',
            name='para_3',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recommendedmeals',
            name='para_4',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
