# Generated by Django 3.2.5 on 2022-05-08 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detoxa_services', '0101_auto_20220423_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detoxa_services.doctors')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detoxa_services.users')),
            ],
        ),
    ]
