# Generated by Django 3.2.5 on 2022-05-13 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detoxa_services', '0107_auto_20220513_2151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordertransaction',
            old_name='orde',
            new_name='order',
        ),
    ]
