# Generated by Django 3.2.5 on 2022-05-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detoxa_services', '0108_rename_orde_ordertransaction_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_gst',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='order_total_without_gst',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
