# Generated by Django 3.2.5 on 2022-05-14 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detoxa_services', '0110_ordertransaction_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100, null=True)),
                ('account_holder_name', models.CharField(max_length=100, null=True)),
                ('account_number', models.CharField(max_length=100, null=True)),
                ('ifsc_code', models.CharField(max_length=100, null=True)),
                ('branch_name', models.CharField(max_length=100, null=True)),
                ('account_type', models.CharField(max_length=100, null=True)),
                ('branch_address', models.CharField(max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('is_doctor', models.BooleanField(default=False)),
                ('is_therapist', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detoxa_services.users')),
            ],
            options={
                'db_table': 'bank_details',
                'managed': True,
            },
        ),
    ]
