# Generated by Django 3.2.5 on 2022-05-15 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detoxa_services', '0112_usermedicalreport_user_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermedicalreport',
            name='year',
            field=models.CharField(default='', max_length=100),
        ),
    ]
