# Generated by Django 3.2.5 on 2022-05-15 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detoxa_services', '0113_usermedicalreport_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermedicalreport',
            name='user_section',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled'), ('Dispatched', 'Dispatched'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered')], max_length=255),
        ),
    ]
