# Generated by Django 3.2.5 on 2022-05-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detoxa_services', '0114_auto_20220515_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home', models.BooleanField(default=True)),
                ('growth_tracker', models.BooleanField(default=True)),
                ('eyesight_tracker', models.BooleanField(default=True)),
                ('vaccination_tracker', models.BooleanField(default=True)),
                ('food_nutrition_tracker', models.BooleanField(default=True)),
                ('hand_eye_tracker', models.BooleanField(default=True)),
                ('learnability_tracker', models.BooleanField(default=True)),
                ('analytical_tracker', models.BooleanField(default=True)),
                ('motorskill_tracker', models.BooleanField(default=True)),
                ('skin_tracker', models.BooleanField(default=True)),
                ('hair_tracker', models.BooleanField(default=True)),
                ('consultation', models.BooleanField(default=True)),
                ('therapy', models.BooleanField(default=True)),
                ('subscription', models.BooleanField(default=True)),
                ('covid_19', models.BooleanField(default=True)),
                ('blogs', models.BooleanField(default=True)),
                ('child_kits', models.BooleanField(default=True)),
                ('contact', models.BooleanField(default=True)),
            ],
        ),
    ]
