# Generated by Django 3.2.5 on 2022-05-21 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detoxa_services', '0116_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_discount',
            field=models.FloatField(default=0),
        ),
    ]
