# Generated by Django 3.2.5 on 2022-05-22 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detoxa_services', '0117_order_order_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100, null=True)),
                ('invoice_date', models.DateTimeField(auto_now_add=True)),
                ('invoice_amount', models.CharField(max_length=100, null=True)),
                ('invoice_url', models.URLField()),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='detoxa_services.ordertransaction')),
            ],
        ),
    ]
