# Generated by Django 3.2.5 on 2022-05-23 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detoxa_services', '0119_invoice_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourites',
            name='therapist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='detoxa_services.therapist'),
        ),
        migrations.AlterField(
            model_name='favourites',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='detoxa_services.doctors'),
        ),
    ]
