# Generated by Django 3.2.5 on 2022-06-01 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detoxa_services', '0121_auto_20220527_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='updated',
        ),
    ]
